#!/usr/bin/env perl
use warnings;
use strict;

# See http://www.w3.org/TR/html401/interact/forms.html#edef-SELECT if curious
# and see http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html
# http://paulsturgess.co.uk/articles/show/23-select-and-collect-with-conditions-in-ruby-on-rails ( October 2010 )

#### Begin section: Edit these four variables for the spin box to the foreign key ####
my $child = 'ad'; # The child table singularized

my $foreign_key = 'city_id'; # The foreign key in the child table
my $foreign_model = 'City'; # The model of the parent table
my $foreign_attribute = 'name'; # The thing you want to lookup in the foreign table

#### End section: Edit these variables ####

my $spin_box = &spin_box;
open( my $out, ">>", "${child}_${foreign_model}.html.erb");
print $out "$spin_box\n";

sub spin_box {
    my $spin_box = "<%= select(\"$child\", \"$foreign_key\", $foreign_model.find(:all).collect { |p| [p.$foreign_attribute, p.id]}) %>";
    return $spin_box;
}
